/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SMDUI;

import javax.swing.*;
/**
 *
 * @author Alec Shunnarah
 */
public class ProductView extends javax.swing.JFrame {

    /**
     * Creates new form AddNewProduct
     */
    public ProductView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        ProductNameText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ProductPriceText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        InitialStockText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        VendorNameText = new javax.swing.JTextField();
        SaveProductBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ProductIDText = new javax.swing.JTextField();
        LoadProductBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Product Name:");

        jLabel2.setText("Price:");

        jLabel3.setText("Initial Stock:");

        jLabel4.setText("Vendor:");

        SaveProductBtn.setText("Save Product");
        SaveProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveProductBtnActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Product ID");

        ProductIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductIDTextActionPerformed(evt);
            }
        });

        LoadProductBtn.setText("Load Product");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ProductIDText)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(ProductNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(75, 75, 75))
                            .addComponent(InitialStockText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2)
                                .addComponent(VendorNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                .addComponent(ProductPriceText))
                            .addComponent(LoadProductBtn))
                        .addGap(79, 79, 79))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(SaveProductBtn))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoadProductBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VendorNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProductPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 148, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProductNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InitialStockText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(SaveProductBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // "Cancel" button navigates back to ManageProducts page
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new HomeUI().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    // create product button saves the information into a MySQL database
    private void SaveProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveProductBtnActionPerformed
        String name, vendor;
        double price, count;
        name = ProductNameText.getText();
        price = Double.parseDouble(ProductPriceText.getText());
        count = Double.parseDouble(InitialStockText.getText());
        vendor = VendorNameText.getText();
        
    }//GEN-LAST:event_SaveProductBtnActionPerformed

    private void ProductIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductIDTextActionPerformed

    public JButton getBtnLoad(){
        return LoadProductBtn;
    }
    
    public JButton getBtnSave(){
        return SaveProductBtn;
    }
    
    public JTextField getTxtProductName() {
        return ProductNameText;
    }

    public JTextField getTxtProductPrice() {
        return ProductPriceText;
    }

    public JTextField getTxtProductQuantity() {
        return InitialStockText;
    }
    
    public JTextField getTxtProductID(){
        return ProductIDText;
    }
    
    public JTextField getTxtVendorName(){
        return VendorNameText;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InitialStockText;
    private javax.swing.JButton LoadProductBtn;
    private javax.swing.JTextField ProductIDText;
    private javax.swing.JTextField ProductNameText;
    private javax.swing.JTextField ProductPriceText;
    private javax.swing.JButton SaveProductBtn;
    private javax.swing.JTextField VendorNameText;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
